[project]
name = "mockserve"
version = "0.1.0"
description = "Simple API Mocking Tool"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]
